// Copies ABI + creation bytecode from Foundry's output into src/contracts so
// the site can read, write and deploy the contracts. Run after `forge build`:
// `npm run abi`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const out = new URL("../src/contracts/", import.meta.url);
mkdirSync(out, { recursive: true });

for (const [file, name, varName] of [
  ["OierAccount.sol", "OierAccount", "oierAccount"],
  ["OierAccountFactory.sol", "OierAccountFactory", "oierAccountFactory"],
]) {
  const artifact = JSON.parse(readFileSync(new URL(`../contracts/out/${file}/${name}.json`, import.meta.url), "utf8"));
  writeFileSync(
    new URL(`${varName}.ts`, out),
    "// Generated by scripts/export-abi.mjs. Do not edit by hand.\n" +
      `export const ${varName}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n` +
      `export const ${varName}Bytecode = "${artifact.bytecode.object}" as const;\n`,
  );
  console.log(name, "abi entries:", artifact.abi.length, "creation bytes:", (artifact.bytecode.object.length - 2) / 2);
}
